### ISSUE TITLE
Use a different plugin ID from the forked source `jpcima/ysfx`

### ISSUE THREAD

**Issue by tkna91** [JoepVanlier/ysfx#44]
**Is your feature request related to a problem? Please describe.**

It seems that `JoepVanlier/ysfx` uses the same plugin ID as the following forked source, so that only one of the VST3 plugins can be used when using REAPER or Renoise.
https://github.com/jpcima/ysfx

https://github.com/user-attachments/assets/c1bb7332-e2ec-4b46-b8a6-cc452d9c9b24

**Describe the solution you'd like**

I wish I could solve this problem by separating the plugin IDs.
I apologize for the inconvenience, but please review and investigate.

**Additional context**

Environment:
- OS: Arch Linux x86_64
- WM: sway
- ysfx-saike-mod-git 0.0.22.r0.gf160367-1
- ysfx-git 1:0.0.0.r244.8077347-4
- reaper 7.22-1
- renoise 3.4.4-1
- linux 6.10.8.arch1-1
- pipewire 1:1.2.3-1
- mesa 1:24.2.1-1

**Comment by JoepVanlier** [comment]
Thanks for bringing this to my attention! I thought I had already changed this by updating the product name in the cmake file, but it seems I likely need to add a plugin name as well.

I will look into this tonight. I'll report back when I know more.

**Comment by JoepVanlier** [comment]
Does this fix it? [Linux 64-bit VST3.zip](https://github.com/user-attachments/files/16936550/Linux.64-bit.VST3.zip)

**Comment by tkna91** [comment]
REAPER solved the problem.
Renoise does not seem to work.
I did reload the plugin.
I am not sure, does it not accept VST3i?

https://github.com/user-attachments/assets/ec8dcd04-ce55-40af-9799-6d300380eafa

**Comment by tkna91** [comment]
I don't know if this is the cause, but it seems to work in the previous VST3 state.

https://github.com/user-attachments/assets/982917a6-d846-4ff6-a020-2d3510e88a25

**Comment by JoepVanlier** [comment]
I'm confused to be honest.

Where did you place the VST3? Is it possible that there are multiple versions still shadowing each-other?

I think VST3s are supposed to be in a particular folder. Might be worth checking the following locations if there's another plugin shadowing the current version:
![image](https://github.com/user-attachments/assets/99593f3a-560f-42ca-a9d4-bc68aca8ea59)

Is it possible to do a hard refresh somehow?

![renoise_test](https://github.com/user-attachments/assets/2e01ca00-ffb6-4007-b9de-a6e88471e560)

**Comment by JoepVanlier** [comment]
Maybe to go back a few steps, why do you need to install them side by side? I don't think I changed the file format, so things should be forward compatible.

This is a bit of a conundrum. Changing the plugin name now, would break the projects of people that have already made projects with the current one. That said, I agree that I should probably use a new name to make sure I don't clash with other forks and/or the original. And it's better to probably rip off the band-aid early.

I think the best course of action is to rename the entirely plugin once now to ensure that people who have existing projects, do not lose their older projects; but that people that have none can just delete the old version and move on with the new one.

Could you please try the following build with the name `ysfx-s`: [Linux 64-bit VST3.zip](https://github.com/user-attachments/files/16971112/Linux.64-bit.VST3.zip)

See if that one shows up correctly.

**Comment by tkna91** [comment]
Indeed, in my case, I only reported it because I had a question about the fact that I could only use one of them, even though they have different names, but for practical purposes, I have no problem with it so far.
If it were possible to handle it interchangeably with the previous ysfx plugin, I think I might rather have the same plugin ID.
But since the names are different, would that not be the case?

I tried ysfx-s and REAPER looks fine.
I checked a little more in Renoise and it seems that you have to add it to both Plugin and TrackDSP to use it as a VST3 instrument.

https://github.com/user-attachments/assets/0958bb67-af3b-45a8-835e-335ce39b7579

The master in the repository seems to be fine and can be used as a VST3 instrument by simply adding it to Plugin.

https://github.com/user-attachments/assets/5605d88d-4700-40e2-b493-a95ea8d4408d

**Comment by JoepVanlier** [comment]
I have found out a bunch more stuff. It seems renoise keeps a cache, even if you enter rescan VSTs. So to do a clean test, you should ideally, really hard clear the cache for every test. That means closing renoise, and deleting some files (or moving them). The problem with not doing that is that things may show up that are actually in a weird state. For instance, you may see a cached effect version in the instrument, that will load, but then show an error message. Something like this:

![image](https://github.com/user-attachments/assets/4d0e623e-2f11-4dae-a79c-bf79ca357d35)

Anyways, on linux those files should be located in ~/.renoise/V3.x.x/. The files to delete/move are called `CachedVST3s_x64.db` and `CachedFailedVST3s_x64.db`. Relaunching renoise after this will trigger a rescan.

It's possible that you were already doing this, but for me this was confounding my testing locally, so it's good to make sure. 

It also seems that in the plugin window, renoise only allows VSTis, while in the sampler effect window it only allows non-VSTis. Renoise is not alone in this. I've since learned many other DAWs do this. This means I will have to build two unique variants of the plugin (which I will happily do).

Here is another zip to test: [Linux 64-bit VST3.zip](https://github.com/user-attachments/files/16999592/Linux.64-bit.VST3.zip)

You will need to add both VST3s. One will be called `ysfx-s` and the other `ysfx-s FX`.

Remember to hard-clear your cache first. Also, thank you so much for your help with this.

**Comment by tkna91** [comment]
1. uninstall `ysfx-saike-mod`
1. delete the following
  - `CachedVST3s_x64.db`
  - `CachedFailedVST3s_x64.db`
3. Renoise->Preferences->Plug/Misc->Rescan
4. add the following
  - `$HOME/.vst3/ysfx-s.vst3`
  - `$HOME/.vst3/ysfx-s FX.vst3`

#### What appears to be a defect
- There is `ysfx FX` in `Plugins`
![image](https://github.com/user-attachments/assets/345f4473-793d-44b8-95ca-099637c41a57)

#### As far as a quick check, else looks fine
https://github.com/user-attachments/assets/039fa1c0-096c-4331-8bb6-11311920d8cd

**Comment by tkna91** [comment]
Coexistence with `ysfx`, the previous forked source, appears to be fine.
Since `ysfx` is not vst3i, it was probably not originally available in Plugins.

https://github.com/user-attachments/assets/5c342f60-6824-4721-bc9b-8aeb718d99d5

Close it to your liking.
This is useful. Thank you!

**Comment by JoepVanlier** [comment]
Resolved in https://github.com/JoepVanlier/ysfx/pull/47

**Comment by SpotlightKid** [comment]
The plugin still seems to have the same VST3 plugin ID as the original:
 
![ysfx_plugin_id](https://github.com/user-attachments/assets/5a5d0ac6-d4b4-4278-947b-7ec6cf572989)

(Carla plugin selector window)

Compiled today from commit 51bbf27 using this [AUR VCS package](https://aur.archlinux.org/packages/ysfx-saike-mod-git).

**Comment by SpotlightKid** [comment]
Sorry, disregard my previous comment. Apparently my package build was using an old build artefact.

**Comment by SpotlightKid** [comment]
Everything ok now:

![ysfx_plugin_id-new](https://github.com/user-attachments/assets/e5e83ce2-f0b3-4dc9-a8db-52139e09a1f7)
